#version 450

#include "../PixelGridComputeGlobals.glsl"

layout (local_size_x = 64, local_size_y = 1, local_size_z = 1) in;
void main()
{
    BoundaryCheck();

    SetupPixelVars(middleCenter, gl_GlobalInvocationID.x);

    GetWritePixel(middleCenter) = GetPixel(middleCenter);

    uvec2 position = GetPixelPosition(middleCenter);

    viewportPixels[PositionToIndex(position)] = GetPixel(middleCenter);
}